sudo: required
services:
  - docker

before_install:
  - docker build -t antonioxzxy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antonioxzxy/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-820807075405"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"