sudo: required
services:
  - docker

before_install:
  - docker build -t antonioxzxy/docker-react -f Dockerfile.dev .

script:
  - docker run antonioxzxy/docker-react npm run test -- --coverage

# language:node_js
# node_js:
#   - "8"